/**
 * Hardcoded Bangalore Destination Nodes for Demo
 * 
 * This file contains sample destination data for Bangalore including:
 * - Base areas (neighborhoods)
 * - Adventure activities
 * - Must-try food spots
 * - Shopping destinations
 * 
 * Used for demonstrating destination-local view functionality.
 */

import { PartnerNodeRecord } from '@/lib/supabase';

// Bangalore destination bounding box (approx 50km radius from center)
export const BANGALORE_BBOX = {
    north: 13.1358,
    south: 12.7342,
    east: 77.8025,
    west: 77.3498,
    center: { lat: 12.9716, lng: 77.5946 }
};

// POI Category types for filtering
export type PoiCategory = 'base' | 'activity' | 'food' | 'shopping' | 'stay';

// Extended node type with POI category
export interface DestinationNode extends Omit<PartnerNodeRecord, 'type'> {
    type: 'stay';
    poi_category: PoiCategory;
    destination_id: string;
    themes?: string[];
    ideal_for?: string[];
    description: string;
}

// Main Bangalore destination node
export const BANGALORE_DESTINATION: DestinationNode = {
    id: 'destination-bangalore',
    name: 'Bengaluru',
    type: 'stay',
    poi_category: 'base',
    destination_id: 'destination-bangalore',
    description: 'India\'s Silicon Valley - a vibrant hub for startups, craft beer, and cosmopolitan culture.',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    features: ['Startups', 'Nightlife', 'Craft Beer', 'Tech Hub'],
    status: 'active',
    themes: ['Startup & Social Hub', 'Digital Nomads', 'Lifestyle & Nightlife'],
};

// Bangalore Base Areas (neighborhoods)
export const BANGALORE_BASES: DestinationNode[] = [
    {
        id: 'blr-base-indiranagar',
        name: 'Indiranagar',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Bengaluru\'s most cosmopolitan neighborhood with tree-lined avenues, craft breweries, boutique cafes, and upscale shopping.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9783692,
        longitude: 77.6408356,
        features: ['Craft beer', 'Cafés', 'Shopping', 'Music gigs', 'Metro access'],
        status: 'active',
        ideal_for: ['Backpackers', 'Foodies', 'Couples', 'Party lovers', 'Solo Travellers'],
    },
    {
        id: 'blr-base-koramangala',
        name: 'Koramangala',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'The startup capital of India, buzzing with young energy, co-working spaces, and endless eateries.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9352403,
        longitude: 77.624532,
        features: ['Startups', 'Street food', 'Nightlife', 'Bookstores', 'Urban culture'],
        status: 'active',
        ideal_for: ['Digital Nomads', 'Students', 'Foodies', 'Entrepreneurs', 'Socializers'],
    },
    {
        id: 'blr-base-mgroad',
        name: 'MG Road & CBD',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'The historic heart of the city with colonial architecture, major museums, and Cubbon Park.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9744461,
        longitude: 77.6069016,
        features: ['Colonial history', 'Parks', 'Museums', 'Street shopping', 'Landmarks'],
        status: 'active',
        ideal_for: ['First-time visitors', 'Families', 'History buffs', 'Walkers'],
    },
    {
        id: 'blr-base-malleswaram',
        name: 'Malleswaram',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'One of the oldest planned neighborhoods offering traditional \'Old Bangalore\' with ancient temples and legendary breakfast spots.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0055113,
        longitude: 77.5692358,
        features: ['Temples', 'Traditional food', 'Flower markets', 'Heritage walks', 'Old-world charm'],
        status: 'active',
        ideal_for: ['Culture seekers', 'Photographers', 'Vegetarian foodies', 'Senior travellers'],
    },
    {
        id: 'blr-base-whitefield',
        name: 'Whitefield',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Massive tech hub with glass-facade IT parks, luxury malls, and premium residential complexes.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9698196,
        longitude: 77.7499721,
        features: ['IT Parks', 'Luxury malls', 'Microbreweries', 'Work-friendly', 'Modern living'],
        status: 'active',
        ideal_for: ['Business travellers', 'Workations', 'Expats', 'Luxury shoppers'],
    },
    {
        id: 'blr-base-basavanagudi',
        name: 'Basavanagudi',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Wide tree-lined streets, heritage homes, and proximity to the famous Lalbagh Botanical Garden.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9405997,
        longitude: 77.5737633,
        features: ['Botanical gardens', 'Literary culture', 'Rock formations', 'Coffee houses', 'Temples'],
        status: 'active',
        ideal_for: ['Nature lovers', 'Families', 'Heritage enthusiasts', 'Slow travellers'],
    },
];

// Bangalore Adventure Activities
export const BANGALORE_ACTIVITIES: DestinationNode[] = [
    {
        id: 'blr-activity-golf',
        name: 'Golf at Bangalore Golf Club',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Bangalore is known as a golfer\'s paradise with some of the country\'s finest golf courses.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9628669,
        longitude: 77.577509,
        features: ['Golf', 'Sports'],
        status: 'active',
    },
    {
        id: 'blr-activity-savanadurga',
        name: 'Savanadurga Hills Trek',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'One of Asia\'s largest monolith hills, perfect for hiking and rock climbing.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.8781307,
        longitude: 77.3192962,
        features: ['Trekking', 'Rock climbing', 'Nature'],
        status: 'active',
    },
    {
        id: 'blr-activity-devarayanadurga',
        name: 'Devarayanadurga Hills Trek',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'A rocky hill station with temples (~2 hr, 73 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0685906,
        longitude: 77.4487361,
        features: ['Trekking', 'Temples', 'Viewpoints'],
        status: 'active',
    },
    {
        id: 'blr-activity-shivaganga',
        name: 'Shivaganga Hills Trek',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'A sacred peak shaped like a Shivalinga (~2 hr, 65 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0955,
        longitude: 77.4621,
        features: ['Trekking', 'Temple', 'Sacred'],
        status: 'active',
    },
    {
        id: 'blr-activity-skandgiri',
        name: 'Skandagiri Hills Night Trek',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Famous for night treks and cloud beds (~1.5 hr, 60 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.3549,
        longitude: 77.6889,
        features: ['Night trek', 'Sunrise', 'Cloud beds'],
        status: 'active',
    },
    {
        id: 'blr-activity-kanakpura',
        name: 'Kanakpura Waterfalls Exploration',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Go for hikes & treks and explore waterfalls.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.5462,
        longitude: 77.4172,
        features: ['Hikes', 'Treks', 'Waterfalls'],
        status: 'active',
    },
    {
        id: 'blr-activity-ramanagara',
        name: 'Rock Climbing at Ramanagara',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Famous filming location of Sholay, perfect for rock climbing and bouldering.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.7254,
        longitude: 77.2830,
        features: ['Rock climbing', 'Bouldering', 'Adventure'],
        status: 'active',
    },
    {
        id: 'blr-activity-kuntibetta',
        name: 'Kuntibetta Trek',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Trek across boulders & granite outcrops (~125 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.6574,
        longitude: 76.3756,
        features: ['Trekking', 'Boulders', 'Granite outcrops'],
        status: 'active',
    },
    {
        id: 'blr-activity-hogenakkal',
        name: 'Hogenakkal Falls Coracle Ride',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Go boating & coracle riding on the river (~125 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.1156412,
        longitude: 77.7798136,
        features: ['Boating', 'Coracle riding', 'Waterfalls'],
        status: 'active',
    },
];

// Bangalore Must-Try Food Spots (from CSV)
export const BANGALORE_FOOD: DestinationNode[] = [
    {
        id: 'blr-food-ctr',
        name: 'CTR (Central Tiffin Room)',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Legendary breakfast spot famous for its crispy Benne Masala Dosa.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9982535,
        longitude: 77.5695357,
        features: ['Breakfast', 'Dosa', 'South Indian'],
        status: 'active',
    },
    {
        id: 'blr-food-veena',
        name: 'Veena Stores',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Famous for its crispy vadas and filter coffee.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0056609,
        longitude: 77.5693243,
        features: ['Breakfast', 'Vada', 'Coffee'],
        status: 'active',
    },
    {
        id: 'blr-food-icehouse',
        name: 'Indian Coffee House',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Iconic coffee house with old-world charm.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9747228,
        longitude: 77.6053375,
        features: ['Coffee', 'Heritage', 'Cafe'],
        status: 'active',
    },
    {
        id: 'blr-food-vidyarthi',
        name: 'Vidyarthi Bhavan',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Iconic 1943-era restaurant known for its signature crispy masala dosa.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9450345,
        longitude: 77.5713723,
        features: ['Heritage', 'Dosa', 'South Indian'],
        status: 'active',
    },
    {
        id: 'blr-food-shivaji',
        name: 'Shivaji Military Hotel',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Famous for non-veg Bangalore-style dishes.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9180061,
        longitude: 77.5739663,
        features: ['Non-veg', 'Local', 'Military hotel'],
        status: 'active',
    },
    {
        id: 'blr-food-onlyplace',
        name: 'The Only Place',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Classic restaurant famous for steaks and sizzlers.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.973234,
        longitude: 77.6034017,
        features: ['Steaks', 'Sizzlers', 'Continental'],
        status: 'active',
    },
    {
        id: 'blr-food-cornerhouse',
        name: 'Corner House',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Legendary ice cream parlor famous for Death by Chocolate.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9701059,
        longitude: 77.6374444,
        features: ['Ice cream', 'Desserts', 'DBC'],
        status: 'active',
    },
    {
        id: 'blr-food-koshys',
        name: 'Koshy\'s',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'An iconic 1940s cafe frequented by journalists, artists, and politicians.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9757463,
        longitude: 77.6014951,
        features: ['Heritage', 'Cafe', 'Continental'],
        status: 'active',
    },
    {
        id: 'blr-food-mtr',
        name: 'Mavalli Tiffin Room (MTR)',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'A 100-year-old institution famous for Rava Idli and traditional South Indian meals.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9805563,
        longitude: 77.640475,
        features: ['Heritage', 'South Indian', 'Thali'],
        status: 'active',
    },
    {
        id: 'blr-food-brahmin',
        name: 'Brahmin\'s Coffee Bar',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'No-frills standing-only spot for soft idlis dipped in chutney with filter coffee.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9539725,
        longitude: 77.568847,
        features: ['Breakfast', 'Filter coffee', 'Local favorite'],
        status: 'active',
    },
    {
        id: 'blr-food-hallimane',
        name: 'Halli Mane',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Traditional Karnataka cuisine in a rustic setting.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9801002,
        longitude: 77.5686948,
        features: ['Karnataka cuisine', 'Traditional', 'Thali'],
        status: 'active',
    },
    {
        id: 'blr-food-janata',
        name: 'Janata Hotel',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Popular for authentic South Indian breakfast.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9991156,
        longitude: 77.5711405,
        features: ['Breakfast', 'South Indian', 'Local'],
        status: 'active',
    },
    {
        id: 'blr-food-udupikrishna',
        name: 'Udupi Krishna Hotel',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Authentic Udupi-style vegetarian fare.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.8831076,
        longitude: 77.5485018,
        features: ['Udupi', 'Vegetarian', 'South Indian'],
        status: 'active',
    },
    {
        id: 'blr-food-dailysushi',
        name: 'Daily Sushi',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Popular spot for fresh sushi and Japanese cuisine.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0625096,
        longitude: 77.5871838,
        features: ['Sushi', 'Japanese', 'Asian'],
        status: 'active',
    },
    {
        id: 'blr-food-magnolia',
        name: 'Magnolia Bakery',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Famous NYC bakery known for cupcakes and banana pudding.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0111072,
        longitude: 77.5548653,
        features: ['Bakery', 'Cupcakes', 'Desserts'],
        status: 'active',
    },
    {
        id: 'blr-food-rameshwaram',
        name: 'Rameshwaram Cafe',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Trending South Indian cafe known for its authentic filter coffee and ghee dosas.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9816796,
        longitude: 77.640918,
        features: ['Trending', 'Coffee', 'South Indian'],
        status: 'active',
    },
    {
        id: 'blr-food-truffles',
        name: 'Truffles',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Famous for its burgers, steaks, and American-style comfort food.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9351892,
        longitude: 77.6247348,
        features: ['Burgers', 'American', 'Casual dining'],
        status: 'active',
    },
    {
        id: 'blr-food-moochmarod',
        name: 'Mooch Marod',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Quirky restaurant with North Indian and fusion dishes.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9263982,
        longitude: 77.7268163,
        features: ['North Indian', 'Fusion', 'Quirky'],
        status: 'active',
    },
    {
        id: 'blr-food-boteco',
        name: 'Boteco',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Brazilian-themed bar and restaurant.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9730759,
        longitude: 77.6148104,
        features: ['Brazilian', 'Bar', 'Nightlife'],
        status: 'active',
    },
    {
        id: 'blr-food-pecos',
        name: 'Pecos',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Legendary rock bar with live music and cold beer.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0356076,
        longitude: 77.5671046,
        features: ['Bar', 'Live music', 'Rock'],
        status: 'active',
    },
    {
        id: 'blr-food-toit',
        name: 'Toit Brewpub',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Bangalore\'s iconic craft brewery with fresh microbrews and great food.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9795441,
        longitude: 77.6406542,
        features: ['Craft beer', 'Brewery', 'Nightlife'],
        status: 'active',
    },
    {
        id: 'blr-food-watsons',
        name: 'Watson\'s',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Popular pub with great cocktails and ambiance.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9909147,
        longitude: 77.6192652,
        features: ['Pub', 'Cocktails', 'Nightlife'],
        status: 'active',
    },
    {
        id: 'blr-food-bobsbar',
        name: 'Bob\'s Bar',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Casual bar chain known for affordable drinks and snacks.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9671903,
        longitude: 77.641187,
        features: ['Bar', 'Affordable', 'Casual'],
        status: 'active',
    },
    {
        id: 'blr-food-abc',
        name: 'Arbor Brewing Company (ABC)',
        type: 'stay',
        poi_category: 'food',
        destination_id: 'destination-bangalore',
        description: 'Microbrewery with craft beers and American-style food.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9703756,
        longitude: 77.6110025,
        features: ['Microbrewery', 'Craft beer', 'American'],
        status: 'active',
    },
];

// Bangalore Shopping Spots (from CSV)
export const BANGALORE_SHOPPING: DestinationNode[] = [
    {
        id: 'blr-shop-commercial',
        name: 'Commercial Street',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A bustling shopping street famous for clothes, jewelry, shoes, and accessories.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.982236,
        longitude: 77.608373,
        features: ['Street shopping', 'Clothes', 'Jewelry'],
        status: 'active',
    },
    {
        id: 'blr-shop-brigade',
        name: 'Brigade Road',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A vibrant hub with high-street brands, street stalls, and a lively atmosphere.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9710429,
        longitude: 77.6069032,
        features: ['High street', 'Brands', 'Nightlife'],
        status: 'active',
    },
    {
        id: 'blr-shop-chickpet',
        name: 'Chickpet Market',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'One of the oldest wholesale markets, known for silk sarees, textiles, and gold.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9709232,
        longitude: 77.5763139,
        features: ['Wholesale', 'Silk sarees', 'Gold'],
        status: 'active',
    },
    {
        id: 'blr-shop-jayanagar',
        name: 'Jayanagar 4th Block Shopping Complex',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A massive complex offering everything from budget clothing and footwear to groceries and local goods.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9299108,
        longitude: 77.5843498,
        features: ['Shopping complex', 'Budget', 'Local goods'],
        status: 'active',
    },
    {
        id: 'blr-shop-blossom',
        name: 'Blossom Book House',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'An iconic bookstore on Church Street with a vast collection of new, used, and rare books.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9750923,
        longitude: 77.6048302,
        features: ['Books', 'Rare finds', 'Culture'],
        status: 'active',
    },
    {
        id: 'blr-shop-antscraft',
        name: 'The Ants Craft',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A sustainable store and cafe offering authentic handicrafts, textiles, and home decor from North East India.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9587058,
        longitude: 77.6424751,
        features: ['Handicrafts', 'North East', 'Sustainable'],
        status: 'active',
    },
    {
        id: 'blr-shop-gonative',
        name: 'Go Native',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A lifestyle store featuring sustainable fashion, home decor, and farm-fresh products.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9628669,
        longitude: 77.577509,
        features: ['Sustainable', 'Fashion', 'Organic'],
        status: 'active',
    },
    {
        id: 'blr-shop-cauvery',
        name: 'Cauvery Handicrafts Emporium',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'Government-run emporium famous for authentic sandalwood carvings and Karnataka artifacts.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9748052,
        longitude: 77.6080535,
        features: ['Handicrafts', 'Sandalwood', 'Souvenirs'],
        status: 'active',
    },
    {
        id: 'blr-shop-mysoresaree',
        name: 'Mysore Saree Udyog',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A legendary store renowned for its massive collection of authentic silk sarees and fabrics.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9814396,
        longitude: 77.6104205,
        features: ['Silk sarees', 'Traditional', 'Fabrics'],
        status: 'active',
    },
    {
        id: 'blr-shop-krmarket',
        name: 'K R Market (City Market)',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'A vibrant wholesale flower and vegetable market offering a sensory local experience.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9656389,
        longitude: 77.5769867,
        features: ['Flowers', 'Local market', 'Photography'],
        status: 'active',
    },
];

// Bangalore Points of Interest (from CSV data)
// Includes: Heritage & Royal Splendour, Spiritual Sanctuaries, Museums Art & Science, 
// Parks & Green Spaces, Serene Lakes, Hikes & Hilltop Views, Adventure & Day Trips, Culture & Crafts
export const BANGALORE_POIS: DestinationNode[] = [
    // Heritage & Royal Splendour
    {
        id: 'blr-poi-palace',
        name: 'Bengaluru Palace',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Home to the royal splendour, featuring Tudor-style architecture.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0035068,
        longitude: 77.5890953,
        features: ['Heritage', 'Palace', 'Architecture'],
        status: 'active',
    },
    {
        id: 'blr-poi-vidhana-soudha',
        name: 'Vidhana Soudha',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'State Legislature building and an impressive architectural landmark.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9796033,
        longitude: 77.5908529,
        features: ['Government', 'Architecture', 'Landmark'],
        status: 'active',
    },
    {
        id: 'blr-poi-attara-kacheri',
        name: 'Attara Kacheri',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'State High Court housed in a magnificent red brick building.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9778874,
        longitude: 77.5925547,
        features: ['Heritage', 'Architecture', 'Colonial'],
        status: 'active',
    },
    {
        id: 'blr-poi-tipu-palace',
        name: 'Tipu Sultan\'s Summer Palace',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Historical structure featuring Indo-Islamic architecture.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9593513,
        longitude: 77.5736415,
        features: ['Heritage', 'Palace', 'History'],
        status: 'active',
    },
    {
        id: 'blr-poi-fort',
        name: 'Bengaluru Fort',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Remains of a 16th-century fort built by Kempe Gowda.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9628018,
        longitude: 77.5758862,
        features: ['Heritage', 'Fort', 'History'],
        status: 'active',
    },
    // Spiritual Sanctuaries
    {
        id: 'blr-poi-st-marys',
        name: 'St. Mary\'s Basilica',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Among the oldest churches in the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9843925,
        longitude: 77.6044189,
        features: ['Church', 'Heritage', 'Spiritual'],
        status: 'active',
    },
    {
        id: 'blr-poi-st-marks',
        name: 'St. Mark\'s Cathedral',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Ornate cathedral built in 1812.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9759108,
        longitude: 77.6004585,
        features: ['Church', 'Heritage', 'Colonial'],
        status: 'active',
    },
    {
        id: 'blr-poi-gavi-gangadhareshwara',
        name: 'Sri Gavi Gangadhareshwara Swamy Devasthana',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Fascinating cave temple known for its astronomical significance.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9482728,
        longitude: 77.5629465,
        features: ['Temple', 'Cave', 'Astronomy'],
        status: 'active',
    },
    {
        id: 'blr-poi-anjaneya-temple',
        name: 'Sri Karya Siddhi Anjaneya Swamy Temple',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Spiritual spot known for its large Hanuman statue.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9384165,
        longitude: 77.5431521,
        features: ['Temple', 'Hanuman', 'Spiritual'],
        status: 'active',
    },
    {
        id: 'blr-poi-bull-temple',
        name: 'Bull Temple',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Home to a huge bull-shaped stone monolith.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9420315,
        longitude: 77.5681024,
        features: ['Temple', 'Heritage', 'Nandi'],
        status: 'active',
    },
    {
        id: 'blr-poi-venkatramana-temple',
        name: 'Venkatramana Temple',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Temple featuring Vijayanagara architecture.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.8993091,
        longitude: 77.5699763,
        features: ['Temple', 'Vijayanagar', 'Architecture'],
        status: 'active',
    },
    // Museums, Art & Science
    {
        id: 'blr-poi-hal-museum',
        name: 'HAL Aerospace Museum',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'India\'s first aviation museum.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.954655,
        longitude: 77.6809058,
        features: ['Museum', 'Aviation', 'History'],
        status: 'active',
    },
    {
        id: 'blr-poi-planetarium',
        name: 'Jawaharlal Nehru Planetarium',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A heaven for space enthusiasts.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9848665,
        longitude: 77.5896341,
        features: ['Planetarium', 'Science', 'Space'],
        status: 'active',
    },
    {
        id: 'blr-poi-ngma',
        name: 'National Gallery of Modern Art',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'An art & culture haven.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9894116,
        longitude: 77.5880553,
        features: ['Art', 'Museum', 'Culture'],
        status: 'active',
    },
    {
        id: 'blr-poi-chitrakala',
        name: 'Karnataka Chitrakala Parishath',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A comprehensive visual arts complex.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9893213,
        longitude: 77.5807437,
        features: ['Art', 'Gallery', 'Culture'],
        status: 'active',
    },
    // Parks & Green Spaces
    {
        id: 'blr-poi-lalbagh',
        name: 'Lalbagh Botanical Gardens',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A sprawling botanical garden and iconic city landmark.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9494158,
        longitude: 77.5846805,
        features: ['Garden', 'Botanical', 'Heritage'],
        status: 'active',
    },
    {
        id: 'blr-poi-cubbon-park',
        name: 'Cubbon Park',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'The central green lung of the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9779291,
        longitude: 77.5951549,
        features: ['Park', 'Nature', 'Jogging'],
        status: 'active',
    },
    {
        id: 'blr-poi-lumbini-gardens',
        name: 'Lumbini Gardens',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A waterfront leisure park.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0434124,
        longitude: 77.6096254,
        features: ['Park', 'Boating', 'Family'],
        status: 'active',
    },
    {
        id: 'blr-poi-bugle-rock',
        name: 'Bugle Rock Park',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A park featuring massive rock formations.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9427052,
        longitude: 77.5694287,
        features: ['Park', 'Rocks', 'History'],
        status: 'active',
    },
    {
        id: 'blr-poi-banyan-tree',
        name: 'Dodda Alada Mara (Big Banyan Tree)',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A ~400 year old banyan tree located ~27 km from the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.909488,
        longitude: 77.3956744,
        features: ['Nature', 'Tree', 'Heritage'],
        status: 'active',
    },
    // Serene Lakes
    {
        id: 'blr-poi-ulsoor-lake',
        name: 'Ulsoor Lake',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A prominent lake located in central Bangalore.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9832468,
        longitude: 77.6199608,
        features: ['Lake', 'Boating', 'Nature'],
        status: 'active',
    },
    {
        id: 'blr-poi-hebbal-lake',
        name: 'Hebbal Lake',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A scenic lake located in the north of the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.0465993,
        longitude: 77.5855829,
        features: ['Lake', 'Birds', 'Nature'],
        status: 'active',
    },
    {
        id: 'blr-poi-btm-lake',
        name: 'BTM Lake',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A popular lake for locals.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9133971,
        longitude: 77.6184106,
        features: ['Lake', 'Walking', 'Nature'],
        status: 'active',
    },
    {
        id: 'blr-poi-agara-lake',
        name: 'Agara Lake',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'A scenic water body in the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.920707,
        longitude: 77.6414418,
        features: ['Lake', 'Walking', 'Birds'],
        status: 'active',
    },
    {
        id: 'blr-poi-bellandur-lake',
        name: 'Bellandur Lake',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'One of the largest lakes in the city.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9357073,
        longitude: 77.6716586,
        features: ['Lake', 'Largest', 'Nature'],
        status: 'active',
    },
    // Hikes & Hilltop Views
    {
        id: 'blr-poi-nandi-hills',
        name: 'Nandi Hills',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'A popular hill fortress to catch a sunrise view (~60 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 13.3838935,
        longitude: 77.6833026,
        features: ['Hills', 'Sunrise', 'Viewpoint'],
        status: 'active',
    },
    // Adventure & Day Trips
    {
        id: 'blr-poi-shivasamudram',
        name: 'Shivasamudram Falls',
        type: 'stay',
        poi_category: 'activity',
        destination_id: 'destination-bangalore',
        description: 'Spot Gaganachukki & Barachukki Waterfalls (~134 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.2997484,
        longitude: 77.1772737,
        features: ['Waterfalls', 'Nature', 'Day trip'],
        status: 'active',
    },
    // Culture & Crafts
    {
        id: 'blr-poi-channapatna',
        name: 'Channapatna Toys Town',
        type: 'stay',
        poi_category: 'shopping',
        destination_id: 'destination-bangalore',
        description: 'Town famous for wooden toys & handicraft (~60 km away).',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.6517602,
        longitude: 77.2086974,
        features: ['Toys', 'Handicrafts', 'Shopping'],
        status: 'active',
    },
    {
        id: 'blr-poi-groundnut-festival',
        name: 'Kadalekayi Parishe (Groundnut Festival)',
        type: 'stay',
        poi_category: 'base',
        destination_id: 'destination-bangalore',
        description: 'Held in December in Basavanagudi to celebrate the crop yield.',
        city: 'Bengaluru',
        country: 'India',
        latitude: 12.9420315,
        longitude: 77.5681024,
        features: ['Festival', 'Culture', 'Local'],
        status: 'active',
    },
];

// All Bangalore nodes combined
export const ALL_BANGALORE_NODES: DestinationNode[] = [
    BANGALORE_DESTINATION,
    ...BANGALORE_BASES,
    ...BANGALORE_ACTIVITIES,
    ...BANGALORE_FOOD,
    ...BANGALORE_SHOPPING,
    ...BANGALORE_POIS,
];

// Helper function to check if coordinates are within Bangalore bbox
export function isWithinBangalore(lat: number, lng: number): boolean {
    return (
        lat >= BANGALORE_BBOX.south &&
        lat <= BANGALORE_BBOX.north &&
        lng >= BANGALORE_BBOX.west &&
        lng <= BANGALORE_BBOX.east
    );
}

// Get nodes by category
export function getBangaloreNodesByCategory(category: PoiCategory): DestinationNode[] {
    return ALL_BANGALORE_NODES.filter(node => node.poi_category === category);
}

// Filter nodes visible in local view (when user is in Bangalore)
export function getBangaloreNodesForLocalView(): PartnerNodeRecord[] {
    // Return all Bangalore nodes as PartnerNodeRecord for display
    return ALL_BANGALORE_NODES.map(node => ({
        id: node.id,
        name: node.name,
        type: node.type,
        description: node.description,
        city: node.city,
        country: node.country,
        latitude: node.latitude,
        longitude: node.longitude,
        features: node.features,
        status: node.status,
        website: null,
        twitter: null,
        image: null,
        contact_email: null,
    }));
}
